django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('image_classifier/',include('image_classifier.urls')),
]

image_classifier/urls.py
from django.urls import path
from . import views

app_name='image_classifier'

urlpatterns = [
    path('',views.index,name='index'),
    path('upload/',views.upload_file,name='upload'),
]

image_classifier/models.py
from django.db import models

class UploadImage(models.Model):
    image = models.ImageField(upload_to='uploads/')

image_classifier/views.py
from django.shortcuts import render, redirect
from .models import UploadImage
from django.conf import settings
from django.templatetags.static import static
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import os

# Load your image classification model
model = load_model(os.path.join(settings.BASE_DIR, 'image_classifier_model.h5'))

def predict_image(file_path):
    img=image.load_img(file_path,target_size=(150,150))
    img_array=image.img_to_array(img)
    img_array=np.expand_dims(img_array,axis=0)
    img_array/=255.0
    prediction=model.predict(img_array)
    class_index=np.argmax(prediction)
    classes={}
    i=0
    characters=['brook','chopper','franky','jinbe','luffy','nami','robin','sanji','usopp','zoro']
    for pirate in characters:
        classes[i]=pirate
        i=i+1
    predicted_class=classes[class_index]
    return predicted_class

def index(request):
    return render(request, 'index.html')

def upload_file(request):
    if request.method == 'POST':
        uploaded_image = request.FILES['file']
        image_instance = UploadImage(image=uploaded_image)
        image_instance.save()
        file_path = os.path.join(settings.MEDIA_ROOT, str(image_instance.image))
        prediction = predict_image(file_path)
        return render(request, 'result.html', {'filename': image_instance.image.name, 'prediction': prediction})
    return redirect('image_classifier:index')

image_classifier/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Image Classifier</title>
</head>
<body>
    <h1>Image Classifier</h1>
    <form action="{% url 'image_classifier:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="submit" value="Upload">
    </form>
</body>
</html>

image_classifier/templates/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Image Classifier Result</title>
</head>
<body>
    <h1>Image Classifier Result</h1>
    <p>Uploaded Image: {{ filename }}</p>
    <p>Prediction: {{ prediction }}</p>
</body>
</html>